# Generated by Django 4.1.3 on 2022-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='bureau',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='personne',
            name='specialite',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
