# Generated by Django 4.1.4 on 2022-12-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0004_alter_hopital_idhopital'),
        ('account', '0002_personne_bureau_personne_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='hopital',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docteur_hopital', to='hopital.hopital'),
        ),
    ]
