# Generated by Django 4.1.4 on 2022-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_personne_hopital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
