# Generated by Django 4.1.4 on 2022-12-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_personne_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='NumeroHopital',
        ),
    ]
