# Generated by Django 4.1.4 on 2022-12-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_personne_numerohopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='groupeSanguin',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='personne',
            name='poids',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
