# Generated by Django 4.1.3 on 2022-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrCode'),
        ),
    ]
