# Generated by Django 4.1.3 on 2022-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='qrCode',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='qrCode'),
        ),
    ]
