# Generated by Django 4.1.3 on 2022-11-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0002_alter_dossiermedical_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousmedical',
            name='statut',
            field=models.TextField(default='non confirmé'),
        ),
    ]
