# Generated by Django 4.1.3 on 2022-11-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0003_rename_qr_code_dossiermedical_qrccode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossiermedical',
            old_name='qrCcode',
            new_name='qrCode',
        ),
    ]
