# Generated by Django 4.1.3 on 2022-11-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0003_rendezvousmedical_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='statut',
            field=models.TextField(default='en cours'),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='diagnostic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='medicaments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='pronostic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
