# Generated by Django 4.1.3 on 2022-11-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0004_dossiermedical_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='statut',
            field=models.TextField(blank=True, default='en cours', null=True),
        ),
    ]
