# Generated by Django 4.1.4 on 2022-12-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0005_alter_dossiermedical_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysemedicale',
            name='resultat',
            field=models.CharField(default='Paludisme', max_length=200),
        ),
    ]
