# Generated by Django 4.1.3 on 2022-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0005_rendezvousmedical_date_rv'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousmedical',
            name='typeRV',
            field=models.CharField(default='', max_length=200),
        ),
    ]
