# Generated by Django 4.1.3 on 2022-11-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomHopital', models.CharField(default='', max_length=50, unique=True)),
                ('adresse', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='logoHopital')),
                ('idHopital', models.CharField(default='0', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomService', models.CharField(default='', max_length=50)),
                ('chefService', models.CharField(default='', max_length=50)),
                ('adresse', models.CharField(default='', max_length=50)),
                ('nombreLit', models.IntegerField(default=0)),
                ('nombreLitOccupe', models.IntegerField(default=0)),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.hopital', verbose_name='hopital_service')),
            ],
        ),
    ]
