# Generated by Django 4.1.3 on 2022-11-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='idService',
            field=models.CharField(default='', max_length=50),
        ),
    ]
