# Generated by Django 4.1.3 on 2022-11-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_service_idservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopital',
            name='idResponsable',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='idResponsable',
            field=models.CharField(default='', max_length=50),
        ),
    ]
