# Generated by Django 4.1.3 on 2022-11-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_alter_hopital_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopital',
            name='idHopital',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
