# Generated by Django 4.1.3 on 2022-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0003_hopital_idresponsable_service_idresponsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='idHopital',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
