# Generated by Django 4.1.3 on 2022-11-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0003_hopital_idhopital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='idHopital',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='nomHopital',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
