# Generated by Django 4.1.4 on 2022-12-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0004_alter_hopital_idhopital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopital',
            name='idHopital',
        ),
    ]
