# Generated by Django 4.1.3 on 2022-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0004_alter_hopital_idhopital_alter_hopital_nomhopital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='idHopital',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
