# Generated by Django 4.1.4 on 2022-12-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0005_remove_hopital_idhopital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='idService',
        ),
    ]
