# Generated by Django 4.1.3 on 2022-11-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0007_alter_hopital_nomhopital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='nomHopital',
            field=models.CharField(default='', max_length=50),
        ),
    ]
