# Generated by Django 4.1.3 on 2022-11-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0010_alter_service_nombrelit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nombreLit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='nombreLitOccupe',
            field=models.IntegerField(default=0),
        ),
    ]
