# Generated by Django 4.1.3 on 2022-11-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0011_alter_service_nombrelit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopital',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.hopital', verbose_name='hopital_service'),
        ),
    ]
