# Generated by Django 4.1.3 on 2022-11-21 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVousMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_priseRV', models.DateTimeField(default=django.utils.timezone.now)),
                ('heureDebut', models.CharField(default='10h00', max_length=50)),
                ('heureFin', models.CharField(default='12h00', max_length=50)),
                ('objectRV', models.TextField(default='')),
                ('docteur', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='docteur_rendezvousmedical', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='patient_rendezvousmedical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronostic', models.CharField(default='a', max_length=100)),
                ('diagnostic', models.CharField(default='a', max_length=200)),
                ('medicaments', models.TextField(default='a')),
                ('date_creationDossierMedical', models.DateTimeField(default=django.utils.timezone.now)),
                ('docteur', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='docteur_dossiermedical', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='DossierMedical_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.ImageField(blank=True, default=None, null=True, upload_to='users')),
                ('butAnalyse', models.TextField(default=' ')),
                ('resultat', models.CharField(default=' ', max_length=200)),
                ('observation', models.TextField(default=' ')),
                ('dateAnalyse', models.DateTimeField(default=django.utils.timezone.now)),
                ('docteur', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='docteur_analysemedical', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='AnalyseMedical_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
