# Generated by Django 4.1.3 on 2022-11-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0002_dossiermedical_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossiermedical',
            old_name='qr_code',
            new_name='qrCcode',
        ),
    ]
